# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-04 09:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0001_initial'),
        ('Threads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.CharField(max_length=2000)),
                ('comment_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Login.User')),
                ('comment_thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Threads.Thread')),
            ],
        ),
    ]
