# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-04 17:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Threads', '0002_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment_author',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='comment_text',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='comment_thread',
            new_name='thread',
        ),
        migrations.RenameField(
            model_name='thread',
            old_name='thread_author',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='thread',
            old_name='thread_text',
            new_name='text',
        ),
        migrations.AlterField(
            model_name='thread',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
